Update deployiis.yml

diff --git a/.github/workflows/deployiis.yml b/.github/workflows/deployiis.yml
--- a/.github/workflows/deployiis.yml
+++ b/.github/workflows/deployiis.yml
@@ -1,7 +1,7 @@
-name: CI/CD Pipeline Role
+name: CodeDeploy Test 
+
 on:
   workflow_dispatch:
-
 
 jobs:
   continuous-deployment:
@@ -30,3 +30,28 @@ jobs:
                           --query "deploymentId" --output text)
           echo "Deployment created with ID: ${DEPLOYMENT_ID}"
           echo "::set-output name=deploymentId::${DEPLOYMENT_ID}"
+
+      # Step 3: Wait for 5 seconds and check deployment status in a loop
+      - name: Wait for deployment to complete
+        id: wait-for-deployment
+        run: |
+          deployment_id=${{ steps.deploy.outputs.deploymentId }}
+          while true; do
+            DEPLOYMENT_STATUS=$(aws deploy get-deployment \
+                                --deployment-id $deployment_id \
+                                --query "deploymentInfo.status" --output text)
+            echo "Deployment status: ${DEPLOYMENT_STATUS}"
+            if [[ "${DEPLOYMENT_STATUS}" == "Succeeded" ]]; then
+              echo "Deployment succeeded."
+              break
+            elif [[ "${DEPLOYMENT_STATUS}" == "Failed" ]]; then
+              echo "Deployment failed."
+              exit 1
+            elif [[ "${DEPLOYMENT_STATUS}" == "Stopped" ]]; then
+              echo "Deployment stopped."
+              exit 1
+            else
+              echo "Deployment status: ${DEPLOYMENT_STATUS}. Waiting for 5 seconds before checking again..."
+              sleep 5
+            fi
+          done
